//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proga2122
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mydatabase1Entities : DbContext
    {
        public mydatabase1Entities()
            : base("name=mydatabase1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Автомобили> Автомобили { get; set; }
        public virtual DbSet<Группа_автомобилей> Группа_автомобилей { get; set; }
        public virtual DbSet<Месячные_пробеги> Месячные_пробеги { get; set; }
        public virtual DbSet<МОЛ> МОЛ { get; set; }

        private static mydatabase1Entities context;

        public static mydatabase1Entities GetContext()
        {
            if (context == null)
            {
                context = new mydatabase1Entities();
            }
            return context;
        }
    }
}
