//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proga2122
{
    using System;
    using System.Collections.Generic;
    
    public partial class Автомобили
    {
        public int Государственный_номер { get; set; }
        public string Марка_автомобиля { get; set; }
        public Nullable<int> Код_группы { get; set; }
        public Nullable<int> Первоначальная_стоимость { get; set; }
        public Nullable<System.DateTime> Дата_ввода_в_эксплуатацию { get; set; }
        public string Пробег_на_начало_года { get; set; }
        public Nullable<int> Стоимость_автомобиля_на_начало_года { get; set; }
        public string Табельный_номер_материально_ответственного_лица { get; set; }
    }
}
